/**
 * Download the BrickLink wanted-list XML for a store's latest assessment.
 *
 * This route SERVES a stored file; it never builds one. The XML is generated by
 * scripts/store-assessment.ts at scan time, because that is the only point at which the
 * full scored lot set exists — the persisted `assessment` blob keeps just a top-N slice
 * per section, so a list assembled here would be a partial cart that looks complete.
 *
 * A run predating the export (or one whose filter matched nothing) has no XML, and this
 * returns 404 with a reason rather than an empty <INVENTORY/> that BL would happily
 * accept and turn into an empty wanted list.
 */
import { NextResponse } from 'next/server';
import { requireUser } from '@/lib/api/require-user';

export const dynamic = 'force-dynamic';

interface WantedRow {
  scanned_at: string;
  mode: string;
  wanted_list_xml: string | null;
  wanted_list_meta: { min_str?: number; entries?: number } | null;
}

export async function GET(_request: Request, { params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const { supabase, unauthorized } = await requireUser();
  if (unauthorized) return unauthorized;

  const { data, error } = await supabase
    .from('store_assessments')
    .select('scanned_at,mode,wanted_list_xml,wanted_list_meta')
    .eq('store_slug', slug)
    .order('scanned_at', { ascending: false })
    .limit(1)
    .maybeSingle<WantedRow>();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
  if (!data) {
    return NextResponse.json({ error: `No assessment for ${slug}` }, { status: 404 });
  }
  if (!data.wanted_list_xml) {
    return NextResponse.json(
      {
        error:
          'This run has no wanted list — it predates the export, or no buyable lot cleared the STR filter. Re-run the store assessment to generate one.',
        scannedAt: data.scanned_at,
      },
      { status: 404 }
    );
  }

  // Slug is user-controlled and lands in a header; strip anything that could break the
  // filename or smuggle a second header field into it.
  const safeSlug = slug.replace(/[^A-Za-z0-9._-]/g, '_');
  const date = data.scanned_at.slice(0, 10);

  return new NextResponse(data.wanted_list_xml, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Content-Disposition': `attachment; filename="wanted-${safeSlug}-${date}.xml"`,
      // Assessments are re-run nightly; a cached copy would hand back yesterday's cart.
      'Cache-Control': 'no-store',
    },
  });
}
