/**
 * eBay Listing Creation Types
 *
 * Type definitions for the "Create eBay Listing" feature including
 * request/response types, progress tracking, and AI-generated content.
 */

// ============================================
// Enums
// ============================================

/**
 * Description style options for AI-generated content
 */
export type DescriptionStyle =
  | 'Minimalist'
  | 'Standard'
  | 'Professional'
  | 'Friendly'
  | 'Enthusiastic';

/**
 * Listing type options
 */
export type ListingType = 'live' | 'scheduled';

/**
 * Status of a listing creation operation
 */
export type ListingCreationStatus =
  | 'started'
  | 'in_progress'
  | 'completed'
  | 'failed'
  | 'cancelled';

// ============================================
// Request Types
// ============================================

/**
 * Best Offer configuration
 */
export interface BestOfferConfig {
  /** Whether Best Offer is enabled (default: true) */
  enabled: boolean;
  /** Auto-accept threshold percentage (default: 95) */
  autoAcceptPercent: number;
  /** Auto-decline threshold percentage (default: 75) */
  autoDeclinePercent: number;
}

/**
 * Image data for listing creation (base64 variant - legacy)
 */
export interface ListingImageBase64 {
  /** Unique identifier for the image */
  id: string;
  /** Original filename */
  filename: string;
  /** Base64-encoded image data */
  base64: string;
  /** MIME type */
  mimeType: 'image/jpeg' | 'image/png' | 'image/webp';
  /** Whether this image has been enhanced */
  enhanced: boolean;
}

/**
 * Image data for listing creation (URL variant - preferred)
 */
export interface ListingImageUrl {
  /** Unique identifier for the image */
  id: string;
  /** Original filename */
  filename: string;
  /** URL to the uploaded image (Supabase Storage) */
  url: string;
  /** MIME type */
  mimeType: 'image/jpeg' | 'image/png' | 'image/webp';
  /** Whether this image has been enhanced */
  enhanced: boolean;
}

/**
 * Image data for listing creation
 * Supports both base64 (legacy) and URL (preferred) formats
 */
export type ListingImage = ListingImageBase64 | ListingImageUrl;

/**
 * Type guard to check if image has URL
 */
export function isListingImageUrl(image: ListingImage): image is ListingImageUrl {
  return 'url' in image && typeof image.url === 'string';
}

/**
 * Type guard to check if image has base64
 */
export function isListingImageBase64(image: ListingImage): image is ListingImageBase64 {
  return 'base64' in image && typeof image.base64 === 'string';
}

/**
 * Request payload for creating an eBay listing
 */
export interface ListingCreationRequest {
  /** Inventory item ID to create listing for */
  inventoryItemId: string;

  /** Listing price in GBP */
  price: number;

  /** Best Offer configuration */
  bestOffer: BestOfferConfig;

  /** Photos for the listing */
  photos: ListingImage[];

  /** Whether to apply eBay image optimization */
  enhancePhotos: boolean;

  /** Description style for AI generation */
  descriptionStyle: DescriptionStyle;

  /** Optional template ID to use */
  templateId?: string;

  /** Listing type (draft, live, or scheduled) */
  listingType: ListingType;

  /** Scheduled publish date (ISO string) - required if listingType is 'scheduled' */
  scheduledDate?: string;

  /** Optional business policy overrides */
  policyOverrides?: {
    fulfillmentPolicyId?: string;
    paymentPolicyId?: string;
    returnPolicyId?: string;
  };

  /** Optional condition description override (bypasses AI generation) */
  conditionDescriptionOverride?: string;

  /** Storage location for the item (updates inventory_items.storage_location) */
  storageLocation?: string;
}

// ============================================
// Progress Types
// ============================================

/**
 * Individual step in the listing creation process
 */
export interface ListingCreationStep {
  /** Step identifier */
  id: string;
  /** Human-readable step name */
  name: string;
  /** Step status */
  status: 'pending' | 'in_progress' | 'completed' | 'failed';
  /** Error message if failed */
  error?: string;
  /** Duration in milliseconds (when completed) */
  durationMs?: number;
}

/**
 * Progress event during listing creation
 */
export interface ListingCreationProgress {
  /** Current step index (0-8) */
  currentStep: number;
  /** Total number of steps */
  totalSteps: number;
  /** Overall progress percentage (0-100) */
  percentage: number;
  /** Current step name */
  stepName: string;
  /** Detailed message for current action */
  message: string;
  /** All steps with their statuses */
  steps: ListingCreationStep[];
}

// ============================================
// AI Generated Content Types
// ============================================

/**
 * Item specifics generated by AI
 */
export interface AIItemSpecifics {
  /** Brand (always "LEGO" for LEGO items) */
  Brand: string;
  /** LEGO theme (e.g., "Star Wars", "City") */
  'LEGO Theme': string;
  /** LEGO set number */
  'LEGO Set Number': string;
  /** Manufacturer Part Number (same as set number) */
  MPN: string;
  /** Type (e.g., "Complete Set", "LEGO Set") */
  Type?: string;
  /** Piece count */
  'Piece Count'?: string;
  /** Age level (e.g., "16+ Years", "8-11 Years") */
  'Age Level'?: string;
  /** Minifigure count */
  'Minifigure Count'?: string;
  /** Features (e.g., "Includes Minifigure(s)") */
  Features?: string;
  /** Character family (e.g., "Star Wars", "Marvel") */
  'Character Family'?: string;
  /** Official LEGO set name */
  'LEGO Set Name'?: string;
  /** LEGO character (e.g., "Luke Skywalker") */
  'LEGO Character'?: string;
  /** Material (usually "Plastic") */
  Material?: string;
  /** Packaging state */
  Packaging?: string;
  /** Release year */
  'Release Year'?: string;
  /** Year manufactured */
  'Year Manufactured'?: string;
  /** Additional specifics */
  [key: string]: string | undefined;
}

/**
 * AI-generated listing content
 */
export interface AIGeneratedListing {
  /** Generated title (max 80 characters) */
  title: string;
  /** Generated subtitle (max 55 characters) or null */
  subtitle: string | null;
  /** Generated HTML description */
  description: string;
  /** eBay condition ID */
  conditionId: number;
  /** Condition description for used items */
  conditionDescription: string | null;
  /** Item specifics for eBay category */
  itemSpecifics: AIItemSpecifics;
  /** Suggested eBay category ID */
  categoryId: string;
  /** SKU for the inventory item */
  sku: string;
  /** Listing price */
  price: number;
  /** AI confidence score (0-100) */
  confidence: number;
  /** Recommendations for improvement */
  recommendations: string[];
}

// ============================================
// Quality Review Types
// ============================================

/**
 * Individual score breakdown item
 */
export interface QualityScoreItem {
  /** Score for this category */
  score: number;
  /** Feedback for this category */
  feedback: string;
}

/**
 * Category scores for quality review
 */
export interface QualityScoreBreakdown {
  /** Title quality (0-25) */
  title: QualityScoreItem;
  /** Item specifics completeness (0-20) */
  itemSpecifics: QualityScoreItem;
  /** Description quality (0-25) */
  description: QualityScoreItem;
  /** Condition accuracy (0-15) */
  conditionAccuracy: QualityScoreItem;
  /** SEO optimization (0-15) */
  seoOptimization: QualityScoreItem;
}

/**
 * Quality review result from Gemini 3 Pro
 */
export interface QualityReviewResult {
  /** Overall quality score (0-100) */
  score: number;
  /** Letter grade */
  grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'F';
  /** Breakdown by category */
  breakdown: QualityScoreBreakdown;
  /** Critical issues that should be fixed */
  issues: string[];
  /** Non-critical improvement suggestions */
  suggestions: string[];
  /** Things done well */
  highlights: string[];
  /** When the review was completed */
  reviewedAt: string;
  /** AI model used for review */
  reviewerModel: string;
}

// ============================================
// Preview Types
// ============================================

/**
 * Preview data sent to client for user confirmation
 */
export interface ListingPreviewData {
  /** Session ID for this listing creation */
  sessionId: string;
  /** AI-generated listing (may be improved by quality loop) */
  listing: AIGeneratedListing;
  /** Quality review result */
  qualityReview: QualityReviewResult | null;
  /** Whether the quality review failed */
  qualityReviewFailed: boolean;
  /** Quality review error message if failed */
  qualityReviewError?: string;
  /** Listing price */
  price: number;
  /** Photo URLs for preview */
  photoUrls: string[];
}

/**
 * User's confirmation of the preview with any edits
 */
export interface ListingPreviewConfirmation {
  /** Session ID for this listing creation */
  sessionId: string;
  /** Edited listing (may have user changes to title, description, etc.) */
  editedListing: AIGeneratedListing;
  /** Whether the user confirmed (true) or cancelled (false) */
  confirmed: boolean;
}

// ============================================
// Result Types
// ============================================

/**
 * Successful listing creation result
 */
export interface ListingCreationResult {
  /** Whether creation was successful */
  success: true;
  /** eBay listing ID */
  listingId: string;
  /** eBay offer ID (internal) */
  offerId: string;
  /** Direct URL to the listing */
  listingUrl: string;
  /** Final listing title */
  title: string;
  /** Final listing price */
  price: number;
  /** Listing type created */
  listingType: ListingType;
  /** Scheduled date if applicable */
  scheduledDate?: string;
  /** AI-generated content used */
  generatedContent: AIGeneratedListing;
  /** Quality review result (may be pending) */
  qualityReview?: QualityReviewResult;
  /** Whether quality review is still in progress */
  qualityReviewPending: boolean;
  /** Audit record ID */
  auditId: string;
  /** Total creation time in ms */
  totalTimeMs: number;
}

/**
 * Failed listing creation result
 */
export interface ListingCreationError {
  /** Whether creation was successful */
  success: false;
  /** Error message */
  error: string;
  /** Step that failed */
  failedStep: string;
  /** Detailed error information */
  errorDetails?: Record<string, unknown>;
  /** Audit record ID for tracking */
  auditId?: string;
  /** Whether a draft was saved */
  draftSaved: boolean;
  /** Draft ID if saved */
  draftId?: string;
}

// ============================================
// Business Policy Types
// ============================================

/**
 * eBay business policy type
 */
export type PolicyType = 'fulfillment' | 'payment' | 'return';

/**
 * Cached eBay business policy
 */
export interface EbayBusinessPolicy {
  /** Policy ID */
  id: string;
  /** Policy type */
  type: PolicyType;
  /** Policy name */
  name: string;
  /** Whether this is the default policy */
  isDefault: boolean;
  /** Full policy data from eBay */
  data: Record<string, unknown>;
  /** When the policy was cached */
  cachedAt: string;
}

/**
 * Business policies response
 */
export interface BusinessPoliciesResponse {
  /** Fulfillment policies */
  fulfillment: EbayBusinessPolicy[];
  /** Payment policies */
  payment: EbayBusinessPolicy[];
  /** Return policies */
  return: EbayBusinessPolicy[];
  /** Default policies */
  defaults: {
    fulfillmentPolicyId?: string;
    paymentPolicyId?: string;
    returnPolicyId?: string;
  };
}

// ============================================
// Draft Types
// ============================================

/**
 * Saved draft for error recovery
 */
export interface ListingLocalDraft {
  /** Draft ID */
  id: string;
  /** Inventory item ID */
  inventoryItemId: string;
  /** Serialized form data */
  draftData: Omit<ListingCreationRequest, 'inventoryItemId'>;
  /** Error context from failed attempt */
  errorContext?: {
    error: string;
    failedStep: string;
    timestamp: string;
  };
  /** Associated audit ID if available */
  failedAuditId?: string;
  /** When the draft was created */
  createdAt: string;
  /** When the draft was last updated */
  updatedAt: string;
}

// ============================================
// Audit Types
// ============================================

/**
 * Listing creation audit record
 */
export interface ListingCreationAudit {
  id: string;
  userId: string;
  inventoryItemId: string;
  ebayListingId?: string;
  ebayOfferId?: string;
  action: 'create_listing' | 'update_listing' | 'publish_listing' | 'schedule_listing';
  status: ListingCreationStatus;
  listingPrice?: number;
  descriptionStyle?: DescriptionStyle;
  templateId?: string;
  photosEnhanced: boolean;
  photoCount: number;
  listingType?: ListingType;
  scheduledDate?: string;
  bestOfferEnabled: boolean;
  bestOfferAutoAcceptPercent?: number;
  bestOfferAutoDeclinePercent?: number;
  generatedTitle?: string;
  generatedDescription?: string;
  itemSpecifics?: AIItemSpecifics;
  categoryId?: string;
  categoryName?: string;
  aiModelUsed?: string;
  aiConfidenceScore?: number;
  aiRecommendations?: string[];
  aiGenerationTimeMs?: number;
  qualityScore?: number;
  qualityFeedback?: QualityReviewResult;
  qualityReviewTimeMs?: number;
  fulfillmentPolicyId?: string;
  paymentPolicyId?: string;
  returnPolicyId?: string;
  researchSources?: Record<string, unknown>;
  errorMessage?: string;
  errorStep?: string;
  errorDetails?: Record<string, unknown>;
  createdAt: string;
  completedAt?: string;
}

// ============================================
// Constants
// ============================================

/**
 * Default Best Offer configuration
 */
export const DEFAULT_BEST_OFFER_CONFIG: BestOfferConfig = {
  enabled: true,
  autoAcceptPercent: 95,
  autoDeclinePercent: 75,
};

/**
 * Listing creation step definitions
 * 10-step flow with pre-publish quality review
 */
export const LISTING_CREATION_STEPS: Array<{ id: string; name: string }> = [
  { id: 'validate', name: 'Validating inventory data' },
  { id: 'research', name: 'Researching product details' },
  { id: 'policies', name: 'Retrieving eBay policies' },
  { id: 'generate', name: 'Generating listing content' },
  { id: 'review', name: 'Quality review' },
  { id: 'preview', name: 'Preparing preview' },
  { id: 'images', name: 'Processing and uploading images' },
  { id: 'create', name: 'Creating eBay listing' },
  { id: 'update', name: 'Updating inventory' },
  { id: 'audit', name: 'Recording audit trail' },
];

/**
 * Description style options with descriptions
 */
export const DESCRIPTION_STYLES: Array<{
  value: DescriptionStyle;
  label: string;
  description: string;
}> = [
  {
    value: 'Minimalist',
    label: 'Minimalist',
    description: 'Clean and concise - just the essential facts',
  },
  {
    value: 'Standard',
    label: 'Standard',
    description: 'Balanced and informative - covers all key points',
  },
  {
    value: 'Professional',
    label: 'Professional',
    description: 'Formal and detailed - business-like tone',
  },
  {
    value: 'Friendly',
    label: 'Friendly',
    description: 'Warm and approachable - conversational style',
  },
  {
    value: 'Enthusiastic',
    label: 'Enthusiastic',
    description: 'Energetic and persuasive - highlights excitement',
  },
];
